"""update find_for_me_requests

Revision ID: 0c4f6f3d0a91
Revises: 6386177132dd
Create Date: 2025-06-21 17:36:55.883316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c4f6f3d0a91'
down_revision: Union[str, None] = '6386177132dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('find_for_me', sa.Column('response_auction', sa.String(), nullable=True))
    op.add_column('find_for_me', sa.Column('response_lot_id', sa.Integer(), nullable=True))
    op.add_column('find_for_me', sa.Column('is_responded', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('find_for_me', 'is_responded')
    op.drop_column('find_for_me', 'response_lot_id')
    op.drop_column('find_for_me', 'response_auction')
    # ### end Alembic commands ###
