"""add user search history table

Revision ID: 3fd1bcaa9bcc
Revises: d9e172cc8fec
Create Date: 2025-06-16 20:14:26.494301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fd1bcaa9bcc'
down_revision: Union[str, None] = 'd9e172cc8fec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_search_history', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_search_history', 'created_at')
    # ### end Alembic commands ###
