"""remove username from find for me

Revision ID: 4d41953060b1
Revises: db66b688bc35
Create Date: 2025-06-29 13:25:40.925322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d41953060b1'
down_revision: Union[str, None] = 'db66b688bc35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('find_for_me', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('find_for_me', sa.Column('username', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
