"""add username to find for me table

Revision ID: 4ebed1cdb743
Revises: 4963b434be8a
Create Date: 2025-06-29 11:29:59.517032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ebed1cdb743'
down_revision: Union[str, None] = '4963b434be8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('find_for_me', sa.Column('username', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('find_for_me', 'username')
    # ### end Alembic commands ###
