"""Add user_id foreign key to search history

Revision ID: d9e172cc8fec
Revises: a61277c8cb3f
Create Date: 2025-06-15 17:33:53.102148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9e172cc8fec'
down_revision: Union[str, None] = 'a61277c8cb3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_search_history', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_search_history', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_search_history', type_='foreignkey')
    op.drop_column('user_search_history', 'user_id')
    # ### end Alembic commands ###
